server:
  port: 8989
  servlet:
    context-path: /cmfz
    jsp:
      init-parameters:
        development: true
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://49.233.183.155:3306/amitabha?characterEncoding=UTF-8
    username: root
    password: shenyaya@ZHENKU666
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  redis:
    host: 49.233.183.155
    port: 6666
    database: 0
    jedis:
      pool:
        max-wait: -1
mybatis:
  mapper-locations: classpath:com/baizhi/mapper/*.xml
  type-aliases-package: com.baizhi.entity
logging:
  level:
    root: info
    com.baizhi.dao: debug